### ISSUE TITLE
Você consegue criar o Arquivo de dependências usando pip freeze

### ISSUE THREAD

**Issue by fecaridade** [vinebarbosa/aaa#2]
--> pip freeze >> requirements.txt

**Comment by fecaridade** [comment]
dai voce instala esses pacotes com pip install -r requirements.txt

**Comment by vinebarbosa** [comment]
Uhhhh, que dahora, isso eu não sabia

**Comment by vinebarbosa** [comment]
Obrigado amigo

**Comment by fecaridade** [comment]
🐍🐍🐍🐍🐍🐍🐍🐍
